DROP TABLE IF EXISTS Runs;
DROP TABLE IF EXISTS CompletedRuns;
DROP TABLE IF EXISTS Member;

CREATE TABLE Member(
  memberId INTEGER PRIMARY KEY AUTO_INCREMENT
  email  VARCHAR(100) NOT NULL UNIQUE
  password VARCHAR(100)  NOT NULL
);

CREATE TABLE CompletedRuns(
  completedRunsId INTEGER PRIMARY KEY AUTO_INCREMENT
  FOREIGN KEY (Member) REFERENCES Member(memberId)
  FOREIGN KEY (Runs) REFERENCES Runs(runId)
);

CREATE TABLE Runs(
  runId INTEGER PRIMARY KEY AUTO_INCREMENT

);
