DROP TABLE IF EXISTS RunTable;
DROP TABLE IF EXISTS UserTable;

CREATE TABLE UserTable(
  userId INTEGER PRIMARY KEY,
  email  VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(100)  NOT NULL
);

CREATE TABLE RunTable(
  runId INTEGER PRIMARY KEY,
  date TIMESTAMP NOT NULL,
  distance INTEGER NOT NULL,
  time INTEGER NOT NULL,
  pace INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  FOREIGN KEY (userId) REFERENCES UserTable(userId)
);
